package com.hand.model;

// default package
// Generated 2015-9-8 23:11:21 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.Cascade;

/**
* Address generated by hbm2java
*/
@Entity
@Table(name="address")
public class Address implements java.io.Serializable {

     @Id
     @Column(name="address_id")
     private Short addressId;
     @Column(name="address")
     private String address;
     @Column(name="address2")
     private String address2;
     @Column(name="district")
     private String district;
     @Column(name="city_id")
     private short cityId;
     @Column(name="postal_code")
     private String postalCode;
     @Column(name="phone")
     private String phone;
     @Column(name="last_update")
     private Date lastUpdate;
     @OneToMany(cascade={CascadeType.ALL})
     @Cascade(org.hibernate.annotations.CascadeType.DELETE_ORPHAN)
     private Set<Customer> customers = new HashSet<Customer>();

     public Address() {
     }

     public Address(String address, String district, short cityId, String phone, Date lastUpdate) {
          this.address = address;
          this.district = district;
          this.cityId = cityId;
          this.phone = phone;
          this.lastUpdate = lastUpdate;
     }

     public Address(String address, String address2, String district, short cityId, String postalCode, String phone,
               Date lastUpdate) {
          this.address = address;
          this.address2 = address2;
          this.district = district;
          this.cityId = cityId;
          this.postalCode = postalCode;
          this.phone = phone;
          this.lastUpdate = lastUpdate;
          
     }

     public Short getAddressId() {
          return this.addressId;
     }

     public void setAddressId(Short addressId) {
          this.addressId = addressId;
     }

     public String getAddress() {
          return this.address;
     }

     public void setAddress(String address) {
          this.address = address;
     }

     public String getAddress2() {
          return this.address2;
     }

     public void setAddress2(String address2) {
          this.address2 = address2;
     }

     public String getDistrict() {
          return this.district;
     }

     public void setDistrict(String district) {
          this.district = district;
     }

     public short getCityId() {
          return this.cityId;
     }

     public void setCityId(short cityId) {
          this.cityId = cityId;
     }

     public String getPostalCode() {
          return this.postalCode;
     }

     public void setPostalCode(String postalCode) {
          this.postalCode = postalCode;
     }

     public String getPhone() {
          return this.phone;
     }

     public void setPhone(String phone) {
          this.phone = phone;
     }

     public Date getLastUpdate() {
          return this.lastUpdate;
     }

     public void setLastUpdate(Date lastUpdate) {
          this.lastUpdate = lastUpdate;
     }
     
     public Set getCustomers() {
         return this.customers;
    }

    public void setCustomers(Set customers) {
         this.customers = customers;
    }

}
