package com.hand.model;
// default package
// Generated 2015-9-8 23:11:21 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
* Payment generated by hbm2java
*/
@Entity
@Table(name="payment")
public class Payment implements java.io.Serializable {
     @Id
     @Column(name="payment_id")
     private Short paymentId;
     @ManyToOne
     @JoinColumn(name="customer")  // 外键
     private Customer customer;
     @Column(name="staff_id")
     private byte staffId;
     @Column(name="rental_id")
     private Integer rentalId;
     @Column(name="amount")
     private BigDecimal amount;
     @Column(name="payment_date")
     private Date paymentDate;
     @Column(name="last_update")
     private Date lastUpdate;

     public Payment() {
     }

     public Payment(Customer customer, byte staffId, BigDecimal amount, Date paymentDate, Date lastUpdate) {
          this.customer = customer;
          this.staffId = staffId;
          this.amount = amount;
          this.paymentDate = paymentDate;
          this.lastUpdate = lastUpdate;
     }

     public Payment(Customer customer, byte staffId, Integer rentalId, BigDecimal amount, Date paymentDate,
               Date lastUpdate) {
          this.customer = customer;
          this.staffId = staffId;
          this.rentalId = rentalId;
          this.amount = amount;
          this.paymentDate = paymentDate;
          this.lastUpdate = lastUpdate;
     }

     public Short getPaymentId() {
          return this.paymentId;
     }

     public void setPaymentId(Short paymentId) {
          this.paymentId = paymentId;
     }

     public Customer getCustomer() {
          return this.customer;
     }

     public void setCustomer(Customer customer) {
          this.customer = customer;
     }

     public byte getStaffId() {
          return this.staffId;
     }

     public void setStaffId(byte staffId) {
          this.staffId = staffId;
     }

     public Integer getRentalId() {
          return this.rentalId;
     }

     public void setRentalId(Integer rentalId) {
          this.rentalId = rentalId;
     }

     public BigDecimal getAmount() {
          return this.amount;
     }

     public void setAmount(BigDecimal amount) {
          this.amount = amount;
     }

     public Date getPaymentDate() {
          return this.paymentDate;
     }

     public void setPaymentDate(Date paymentDate) {
          this.paymentDate = paymentDate;
     }

     public Date getLastUpdate() {
          return this.lastUpdate;
     }

     public void setLastUpdate(Date lastUpdate) {
          this.lastUpdate = lastUpdate;
     }

}
