package com.hand.model;
// default package
// Generated 2015-9-9 15:46:19 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Rental generated by hbm2java
 */
@Entity
@Table(name="rental")
public class Rental implements java.io.Serializable {
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name="rental_id")
	private Integer rentalId;
	@Column(name="rental_date")
	private Date rentalDate;
	@Column(name="inventory_id")
	private int inventoryId;
	@ManyToOne
    @JoinColumn(name="customer")  // 外键
	private Customer customer;
	@Column(name="return_date")
	private Date returnDate;
	@Column(name="staff_id")
	private byte staffId;
	@Column(name="last_update")
	private Date lastUpdate;

	public Rental() {
	}

	public Rental(Date rentalDate, int inventoryId, Customer customer, byte staffId, Date lastUpdate) {
		this.rentalDate = rentalDate;
		this.inventoryId = inventoryId;
		this.customer = customer;
		this.staffId = staffId;
		this.lastUpdate = lastUpdate;
	}

	public Rental(Date rentalDate, int inventoryId, Customer customer, Date returnDate, byte staffId, Date lastUpdate) {
		this.rentalDate = rentalDate;
		this.inventoryId = inventoryId;
		this.customer = customer;
		this.returnDate = returnDate;
		this.staffId = staffId;
		this.lastUpdate = lastUpdate;
	}

	public Integer getRentalId() {
		return this.rentalId;
	}

	public void setRentalId(Integer rentalId) {
		this.rentalId = rentalId;
	}

	public Date getRentalDate() {
		return this.rentalDate;
	}

	public void setRentalDate(Date rentalDate) {
		this.rentalDate = rentalDate;
	}

	public int getInventoryId() {
		return this.inventoryId;
	}

	public void setInventoryId(int inventoryId) {
		this.inventoryId = inventoryId;
	}

	public Customer getCustomerId() {
		return this.customer;
	}

	public void setCustomerId(Customer customer) {
		this.customer = customer;
	}

	public Date getReturnDate() {
		return this.returnDate;
	}

	public void setReturnDate(Date returnDate) {
		this.returnDate = returnDate;
	}

	public byte getStaffId() {
		return this.staffId;
	}

	public void setStaffId(byte staffId) {
		this.staffId = staffId;
	}

	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

}
